---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates OracleLinux
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: Install updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    ansible.builtin.user:
        name: simone
        groups: root

  - name: add ssh key for simone
    ansible.posix.authorized_key:
      user: simone
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: add sudoers file for simone
    tags: always
    ansible.builtin.copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 288

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and PHP package on Ubuntu
    tags: apache,apache2,ubuntu
    package: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and PHP package on OracleLinux
    tags: apache,oracleserver,httpd
    package: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install apache and PHP package on Rocky
    tags: apache,oracleserver,httpd
    package: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"
 
  - name: start httpd
    tags: apache,httpd,oraclelinux
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "Rocky"

  - name: change email address for httpd serveradmin
    tags: apache,oraclelinux,httpd
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Rocky"
    register: httpd

  - name: restart httpd
    tags: apache,rocky,httpd
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: true
    when: httpd.changed

  - name: copy default html file for the site
    tags: apache,apache2,httpd
    copy:
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
  - name: open firewall-cmd port for httpd
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
    when: ansible_distribution == "Rocky"
    
- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package oraclelinux
    tags: oraclelinux,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: workstation
  become: true
  tasks:
 
   - name: install unzip
     package:
       name: unzip
 
   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root
   